// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PicPaySimplificado.Infrastructure;

#nullable disable

namespace PicPaySimplificado.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.3");

            modelBuilder.Entity("PicPaySimplificado.Domain.Transaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("Amount");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime")
                        .HasColumnName("Created");

                    b.Property<Guid>("ReceiverId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("SenderId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ReceiverId");

                    b.HasIndex("SenderId");

                    b.ToTable("Transactions", (string)null);
                });

            modelBuilder.Entity("PicPaySimplificado.Domain.Users", b =>
                {
                    b.Property<Guid>("_guid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("Guid");

                    b.Property<decimal>("_balance")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18,2)")
                        .HasDefaultValue(0m)
                        .HasColumnName("Balance");

                    b.Property<string>("_email")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasColumnName("Email");

                    b.Property<string>("_fullname")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasColumnName("Fullname");

                    b.Property<string>("_password")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasColumnName("Password");

                    b.Property<string>("_userType")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("UserType");

                    b.HasKey("_guid");

                    b.HasIndex("_email")
                        .IsUnique();

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("PicPaySimplificado.Domain.Transaction", b =>
                {
                    b.HasOne("PicPaySimplificado.Domain.Users", "Receiver")
                        .WithMany("ReceivedTransactions")
                        .HasForeignKey("ReceiverId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PicPaySimplificado.Domain.Users", "Sender")
                        .WithMany("SentTransactions")
                        .HasForeignKey("SenderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Receiver");

                    b.Navigation("Sender");
                });

            modelBuilder.Entity("PicPaySimplificado.Domain.Users", b =>
                {
                    b.OwnsOne("PicPaySimplificado.ValueObject.Document", "_document", b1 =>
                        {
                            b1.Property<Guid>("Users_guid")
                                .HasColumnType("TEXT");

                            b1.Property<string>("DocumentNumber")
                                .IsRequired()
                                .HasColumnType("TEXT")
                                .HasColumnName("Document");

                            b1.Property<int>("UserType")
                                .HasColumnType("INTEGER");

                            b1.HasKey("Users_guid");

                            b1.HasIndex("DocumentNumber")
                                .IsUnique();

                            b1.ToTable("Users");

                            b1.WithOwner()
                                .HasForeignKey("Users_guid");
                        });

                    b.Navigation("_document")
                        .IsRequired();
                });

            modelBuilder.Entity("PicPaySimplificado.Domain.Users", b =>
                {
                    b.Navigation("ReceivedTransactions");

                    b.Navigation("SentTransactions");
                });
#pragma warning restore 612, 618
        }
    }
}
